SELECT @@transaction_isolation;
SELECT @@global.transaction_isolation;



SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ ;
SET GLOBAL TRANSACTION ISOLATION LEVEL REPEATABLE READ;


SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET GLOBAL TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
